# Generated by Django 5.2.6 on 2025-09-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
